url: go.hacdias.com

packages:
  maze:
    repo: github.com/hacdias/maze
    description: Reverse location information.
  eagle:
    repo: github.com/hacdias/eagle
    description: My website's blogging platform.
  indieauth:
    repo: github.com/hacdias/indieauth
  indiekit:
    repo: github.com/hacdias/indiekit
    description: An IndieWeb toolkit in Go.
  indielib:
    repo: github.com/hacdias/indielib
    description: An IndieWeb toolkit in Go.
  xkcd-archiver:
    repo: github.com/hacdias/xkcd-archiver
    description: A cloner of the XKCD comics for archiving purposes.
