tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "ngrok/ngrok"
brew "age"
brew "caddy"
brew "python@3.9"
brew "coreutils"
brew "dnscontrol"
brew "ethereum"
brew "ffmpeg"
brew "findutils"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "hugo"
brew "imagemagick"
brew "ipfs"
brew "jhead"
brew "jq"
brew "mas"
brew "moreutils"
brew "openssh"
brew "pinentry-mac"
brew "starship"
brew "stow"
brew "watch"
brew "wget"
brew "zsh"
cask "discord"
cask "docker"
cask "font-fira-code"
cask "ganache"
cask "gog-galaxy"
cask "google-chrome"
cask "iterm2"
cask "macfuse"
cask "minecraft"
cask "miniforge"
cask "ngrok"
cask "obsidian"
cask "pdf-expert"
cask "pgadmin4"
cask "scroll-reverser"
cask "spotify"
cask "transmission"
cask "veracrypt"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
mas "1Password 7", id: 1333542190
mas "Actions", id: 1586435171
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Black Out", id: 1319884285
mas "Lungo", id: 1263070803
mas "MakePass", id: 1450989464
mas "Microsoft Word", id: 462054704
mas "miele-lxiv", id: 988332475
mas "One Thing", id: 1604176982
mas "Pandan", id: 1569600264
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "Todoist", id: 585829637
