#!/usr/bin/env bash

set -euo pipefail

SRC="/Users/hacdias/Library/Mobile Documents/iCloud~is~workflow~my~workflows/Documents/Project Lifie"
DST="/Users/hacdias/Pictures/Project Lifie"

cd "$SRC"

# Rename all pictures to YYYY-MM-DD
mv "$SRC"/*.jpeg "$DST/"
find . -iname '*jpeg' -exec jhead -n%Y-%m-%d_%H-%M-%S {} +