#!/usr/bin/env bash

git init

# Base .gitignore
echo "thumbs.db" >> .gitignore
echo '*.egg-info' >> .gitignore
echo '*.log' >> .gitignore
echo '*.pyc' >> .gitignore
echo '*.swo' >> .gitignore
echo '*.swp' >> .gitignore
echo '*~' >> .gitignore
echo '.#*' >> .gitignore
echo '.DS_Store' >> .gitignore
echo '.coverage' >> .gitignore
echo '.pydevproject' >> .gitignore
echo '.ropeproject/' >> .gitignore
echo 'build/' >> .gitignore
echo 'dist/' >> .gitignore
echo 'pip-log.txt' >> .gitignore
echo 'node-modules' >> .gitignore

git add .gitignore
git commit -m "Initial commit"
