#!/usr/bin/env bash

set -eou pipefail

set -a # This makes all variables be exported by default.
source ~/scripts/.silos.env
set +a

cd $COLLECTOR_CWD

echo ">>> TRAKT DATA FETCHER"
node ./bin.js trakt sync || telegram "Error while fetching Trakt data"

echo ">>> SWARM DATA FETCHER"
node ./bin.js swarm sync || telegram "Error while fetching Swarm data"

echo ">>> LASTFM DATA FETCHER"
node ./bin.js lastfm sync || telegram "Error while fetching LastFM data"

echo ">>> MINIFLUX DATA FETCHER"
node ./bin.js miniflux sync || telegram "Error while fetching Miniflux data"

echo ">>> UPDATING DATA REPO"
cd $DATA_CWD
git-sync

